rootLogger = INFO, STDOUT

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d [%t] %highlight{%-5level %c{2}: %notEmpty{%X{symbol}: }%msg}%n